### ISSUE TITLE
Missing accounts (committers)

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#102]
I've tried to identify committers' (https://projects.apache.org/committee.html?lucene) GitHub accounts as far as possible. Several accounts were found (I added them to the mapping file), but there are still missing persons/accounts.

- [ ] Bernhard Messer
- [ ] Michael Busch
  -  could be https://github.com/michaelbusch ?
- [ ] Doron Cohen
  - could be https://github.com/doron-cohen or https://github.com/cdoronc or https://github.com/doronchn or https://github.com/doroncohen9 or https://github.com/doroncoh3n or https://github.com/docohen ?
- [ ] Gregory Chanan
- [x] Karl Wright
- [x] Otis Gospodnetic
- [x] Stefan Matheis
- [x] Wolfgang Hoschek
  - could be https://github.com/whoschek ?

**Comment by mocobeta** [comment]
This list includes people who are/were very active in Lucene, but I gave up. 

If you have any information please let me know. cc @mikemccand

**Comment by uschindler** [comment]
One posisbility: Grep through the whole history of the (old) lucene-solr repository searching for their name as committer/author. If you found a hit, copy the commit id and then look up this exact commit using Github Web UI. If the person is then hotlinked there, you found a match. Otherwise there's no way to fix this.

Uwe

**Comment by mikemccand** [comment]
Karl Wright is `daddywri` in both places (plus a couple email addresses) -- I'll push a change.

**Comment by mikemccand** [comment]
> * Otis Gospodnetic

Otis is @otisg on GitHub (I recognize him) -- I'll add his mapping.

**Comment by mocobeta** [comment]
Thank you @mikemccand. 

> Otis is `@otisg` on GitHub (I recognize him) -- I'll add his mapping.

Sorry, I should have recognized it - actually the script found the account as a candidate. Looks like I failed to manually identify the association (there's just one difference between `Otis Gospodnetic` and `Otis Gospodnetić`, a diacritic).

**Comment by mocobeta** [comment]
> Karl Wright is daddywri in both places (plus a couple email addresses) -- I'll push a change.

For this mapping, it was impossible to detect it by the account search strategy I wrote. There are two Jira accounts, `kwright@metacarta.com` and `daddywri`; in Lucene Jira, only the former has been used as issue reporters, and the latter has not appeared even in the candidate list. The past extensive account renaming could affect here, I think we have many similar cases.

**Comment by mocobeta** [comment]
Manual account identification/verification is the most time- and energy-consuming task in the entire work (it took two hours for me only for <100 committers). I don't think we can do the same for the 2000+ contributors, although it'd be technically possible. Maybe I'll try to identify the mapping of the top 100 or 200 contributors if I'm able to take the time.

**Comment by mocobeta** [comment]
> One posisbility: Grep through the whole history of the (old) lucene-solr repository searching for their name as committer/author. If you found a hit, copy the commit id and then look up this exact commit using Github Web UI. If the person is then hotlinked there, you found a match. Otherwise there's no way to fix this.

Thanks for your suggestion - I have already considered apache/lucene history but have not looked at the lucene-solr repo yet. I'll try it if I can find enough energy for this.

**Comment by mocobeta** [comment]
I think I found Stefan Matheis's GH account - https://github.com/steffkes

**Comment by mocobeta** [comment]
> `@whoschek` is Wolfgang Hoschek. 

Thank you @uschindler - added in https://github.com/apache/lucene-jira-archive/commit/836f08afbc748a727b0952e3e5243f6699176810.

**Comment by mocobeta** [comment]
There is one more issue for committers - many committers do not associate their GitHub accounts with [the ASF organization](https://github.com/apache), which means they have no push access to `apache/lucene` and we cannot "assign" them to GitHub issues.

**Comment by whoschek** [comment]
Hi Uwe, Yeah, that's me.
Thanks!
Wolfgang Hoschek

**Comment by mocobeta** [comment]
> I think we'd need to ask committers to link their GitHub account with your ASF account.
> https://infra.apache.org/apache-github.html

I sent an email to committers whose GH account is not linked to any ASF account yet.

**Comment by mocobeta** [comment]
I'm closing this. Thanks for your help.

**Comment by mocobeta** [comment]
Hi @sigram, @areek, @ChrisHegarty, @cmoen, @GregBowyer, @hgadre, @chatman, @DaddyWri, @martijnvg, @otisg, @stanislawosinski, @ovalhub and @whoschek:

I wanted to let you know that I sent an email (DM) about the coming Lucene's GitHub issue migration to your `@apache.org` email address. To make the migration complete, we need your action. Three minutes would be sufficient - please check your inbox.
Thank you.

**Comment by stanislawosinski** [comment]
Hi Tomoko,

I added my GitHub user name at id.apache.org yesterday, this is what I see
when I log in again:

[image: image.png]

I don't see Apache in my list of GitHub organizations yet though. Is there
anything else I need to do?

Thanks,

Stanislaw

**Comment by uschindler** [comment]
@stanislawosinski it is more important to actually link the accounts! https://gitbox.apache.org/boxer/

The process is there. The id.apache.org is only to setup the user names. The actual linking should be done there. Keep in mind that you need 2FA enabled in your GitHub account to actually do this.

**Comment by uschindler** [comment]
For me it looks like this:
![Screenshot_20220802-091323](https://user-images.githubusercontent.com/1005388/182314570-3d261e86-584e-4ad8-8eb5-c6b3139ad4a6.png)

**Comment by mocobeta** [comment]
@stanislawosinski thank you for your cooperation!

And thanks @uschindler for the information. I will send a follow-up email to note about MFA.

**Comment by stanislawosinski** [comment]
Thanks, @uschindler! I've just set up the link and see myself as Apache member on GitHub.

**Comment by martijnvg** [comment]
I've linked my gh and asf accounts:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/580421/183112551-a1e62724-6c4f-4eaa-97d3-717331b5ab3c.png">

**Comment by mocobeta** [comment]
Thank you @martijnvg.
