### ISSUE TITLE
Should we regenerate another full export?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#104]
I know this is a hassle and adds delay, but, we have fixed a number of issues since the last full test export.

And e.g. @msokolov's first comment on this current iteration is just such an example.

If we take another iteration we can bring fresh eyes on the latest changes?

**Comment by mocobeta** [comment]
Yes - I plan another full import. I don't think we need to walk through the complete migration steps written in #7 again, but at least we can pick the most critical parts - conversion and import.

**Comment by mocobeta** [comment]
All issues were successfully imported to https://github.com/mocobeta/forks-migration-test-2/issues with the latest main.
Issue link remapping is ongoing.

**Comment by mocobeta** [comment]
Done.
https://github.com/mocobeta/forks-migration-test-2/issues

Generally it looks fine. I noticed some minor glitches like #109 and #110. I'll address them (if it's easy and safe to fix).
I think we can open an INFRA issue for the migration next week.

**Comment by mocobeta** [comment]
Before opening INFRA issues, I'll try to address issues I found in the latest migration test and run another full import.

**Comment by mikemccand** [comment]
Thanks @mocobeta.

**Comment by mocobeta** [comment]
Hi, here is the latest migration result. All recent improvements (e.g., #128, #131, #136, etc.) are applied.
https://github.com/mocobeta/forks-migration-test-3/issues

**Comment by mocobeta** [comment]
I checked several issues from new to old. I see no degradations from the previous one.

If you are okay with that, the actual migration will be the same as this except for the issue reporter and assignees (the issue reporter should be an ASF bot account and assignees should be correctly set).

**Comment by mikemccand** [comment]
+1, let's close this, yay!!  Thank you @mocobeta!

**Comment by mocobeta** [comment]
Thank you, please open reports if you notice anything. I think we still have some time for small improvements.
