### ISSUE TITLE
Numbered list item is not correctly converted if it follows TAB character

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#112]
Seems to occur only in commitbot's comments.

https://github.com/mocobeta/forks-migration-test-2/issues/10514#issuecomment-1205989333

<img width="949" alt="スクリーンショット 2022-08-08 18 30 36" src="https://user-images.githubusercontent.com/1825333/183386767-eff90c3c-eb6e-451a-8033-49d647fc3025.png">

Looks like it's not easy to fix.

**Comment by mocobeta** [comment]
I tried this, and I'd conclude it's difficult to investigate (while it should be possible).

**Comment by mocobeta** [comment]
Or, we could just convert `\t` to space characters (2 or 4 whitespaces maybe)?

**Comment by mocobeta** [comment]
> Or, we could just convert `\t` to space characters (2 or 4 whitespaces maybe)?

But I can't estimate whether there are no side effects.

**Comment by msokolov** [comment]
Maybe a no-break-space (&#160;) would be safer (less likely to have some special meaning to github markdown parser) than a regular space?

**Comment by mocobeta** [comment]
I think in most cases it's fine to replace `\t` to whitespace or `&#160;`, but noformat or code block can also contain `\t`; modifying any characters can break a code block (I once learned it).

**Comment by mocobeta** [comment]
I finally figured out a solution in #140.
