### ISSUE TITLE
Make a test set for improving markup conversion quality

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#12]
In #1, there are too many patterns where converted markdown can be broken. Can't make sure that an ad-hoc fix for one problem does not introduce another bug.
Instead of arbitrarily choosing examples, it'd be good to have a carefully selected test set that includes various markup combinations.

**Comment by mocobeta** [comment]
Supported block elements in [Jira Text Formatting](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all)

- `-`: not included
- `o`: correctly rendered
- `x`: broken

|Issue|Quote|Bullet list|Numbered list|Noformat/Code|Table|
|-|-|-|-|-|-|
|[LUCENE-10560](https://github.com/mocobeta/sandbox-lucene-10557/issues/10793)|-|-|-|o|-|
[LUCENE-10559](https://github.com/mocobeta/sandbox-lucene-10557/issues/10792)|-|-|-|-|x|
|[LUCENE-10557](https://github.com/mocobeta/migration-test-2/issues/155)|x|x|x|o|x|
|[LUCENE-10544](https://github.com/mocobeta/sandbox-lucene-10557/issues/10777)|x|x|-|o|-|

**Comment by mikemccand** [comment]
> * [LUCENE-2230](https://github.com/mocobeta/sandbox-lucene-10557/issues/2472) - won't fix, maybe not a big problem

Hi @mocobeta -- I couldn't understand what went wrong in this issue?

Indeed, there was at least one comment (I think?) where the author used Markdown (which does not work in Jira, yet many of us forget and use it anyway, just like seeing a naked `bq.` here on GitHub or in emails!) and then the rendering worked on migration!  A surprising benefit of migration ;)

**Comment by mocobeta** [comment]
> Hi @mocobeta -- I couldn't understand what went wrong in this issue?

I meant this comment. This should be plain text, not interpreted as headers.

![Screenshot from 2022-07-10 20-01-27](https://user-images.githubusercontent.com/1825333/178142132-7ba62c9e-6fcc-4c61-add7-0fb08956225e.png)

> Indeed, there was at least one comment (I think?) where the author used Markdown (which does not work in Jira, yet many of us forget and use it anyway, just like seeing a naked bq. here on GitHub or in emails!) and then the rendering worked on migration! A surprising benefit of migration ;)

I don't think unintentional markdowns will be properly rendered after migration. Markdowns in Jira are (correctly) escaped in the converter.

**Comment by mikemccand** [comment]
> I don't think unintentional markdowns will be properly rendered after migration. Markdowns in Jira are (correctly) escaped in the converter.

Oh, I though the original author of that comment (Fuad) indeed meant for those `=======` to become headers, and I was happy that the converter "missed" escaping them.

Here is another example (comment) from that same issue where the "miss" was great -- we properly rendered a code block in the GitHub issue when Jira missed it:

![Screen Shot 2022-07-10 at 8 18 11 AM](https://user-images.githubusercontent.com/796508/178144625-7c179e83-9f2b-4f1d-801c-d293ba5f5737.png)

Original JIra:

![Screen Shot 2022-07-10 at 8 18 02 AM](https://user-images.githubusercontent.com/796508/178144634-b39ce7ee-798d-4618-b9ec-15ccfc7c0a2e.png)

The original comment used block indentation, which MD interprets as code block.

I sort of think this is a feature not a bug?  But, it is not a priority to handle these mixed cases well!  If the converter is escaping some and missing others I think we can let it be, unless it's impacting too many cases.

**Comment by mocobeta** [comment]
> I sort of think this is a feature not a bug? But, it is not a priority to handle these mixed cases well! If the converter is escaping some and missing others I think we can let it be, unless it's impacting too many cases.

I've seen some quote symbols `>` were escaped in the converted results but not sure if this is a "feature" or "bug"... I think there may be mixed situations (some markdowns are preserved as-is and rendered as the authors intended, and some are escaped).

**Comment by mocobeta** [comment]
> Indeed, there was at least one comment (I think?) where the author used Markdown (which does not work in Jira, yet many of us forget and use it anyway, just like seeing a naked `bq.` here on GitHub or in emails!) and then the rendering worked on migration! A surprising benefit of migration ;)

I reviewed the converter library's code again. Your insight is correct - it seems there is no escaping for Markdown, so _if there are no extra space characters that interfere with the frontend_, Markdowns in Jira are rendered in GitHub (as the authors might expect).

**Comment by mocobeta** [comment]
I'm closing this.
