### ISSUE TITLE
Consider removing "Legacy Jira: by" prefix from comments

### ISSUE THREAD

**Issue by vlsi** [apache/lucene-jira-archive#122]
"Legacy Jira: by" does not seem to add much value, however, it makes it harder to read the comments (see https://github.com/mocobeta/forks-migration-test-2/issues/10595#issuecomment-1205993910)

I understand you have to use "bot account" for the import, however, it looks like you could just start the comment with the real username. "legacy jira: by" is excessive.

**Comment by mocobeta** [comment]
I'm fine with removing "Legacy Jira" from the header - what do you think @mikemccand?

**Comment by mikemccand** [comment]
I'm OK with shortening it somehow if we can, but I think the sentiment must remain -- we need to convey this was a migrated comment to future people who didn't even know we did this issue migration.  Maybe "Prior Jira: "?  "Migrated Jira: "?

We could remove the `by` prefix after the : at least?

**Comment by vlsi** [comment]
> I think the sentiment must remain -- we need to convey this was a migrated comment to future people

I just thought the comment date (and the fact it would be created by asfgit account) would be just enough to tell the comment was migrated.

**Comment by mocobeta** [comment]
> we need to convey this was a migrated comment to future people who didn't even know we did this issue migration. Maybe "Prior Jira: "? "Migrated Jira: "?

I'm also inclined to keep suggesting "Jira" (the original source) in the issue descriptions/comments.

**Comment by vlsi** [comment]
How about changing from

[Legacy Jira: by Yuting Gan (@ Yuti-G) on [Jul 10 2022](https://issues.apache.org/jira/browse/LUCENE-10644?focusedCommentId=17564642&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17564642)]

to 

Yuting Gan (@ Yuti-G) ([migrated from JIRA commnt](https://issues.apache.org/jira/browse/LUCENE-10644?focusedCommentId=17564642&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17564642))

?

The date is already present in GitHub UI, so duplicating it does not add much.

**Comment by mikemccand** [comment]
> The date is already present in GitHub UI, so duplicating it does not add much.

+1, I like that.  It can just say "migrated from Jira" (no need to say comment/description)?

**Comment by mocobeta** [comment]
OK makes sense to me, I'll change the header like this.

Yuting Gan (@ Yuti-G) ([migrated from JIRA](https://issues.apache.org/jira/browse/LUCENE-10644?focusedCommentId=17564642&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17564642))

**Comment by mocobeta** [comment]
Addressed in #128.

**Comment by mocobeta** [comment]
#128 was merged - I'm closing this. Thanks @vlsi and @mikemccand for your suggestions.
