### ISSUE TITLE
Consider removing "Legacy JIRA" from the issue descriptions

### ISSUE THREAD

**Issue by vlsi** [apache/lucene-jira-archive#123]
See https://github.com/mocobeta/forks-migration-test-2/issues/1872#issue-1328214873

Does "Legacy" add much value? I do not think so.
Something like "Migrated from [LUCENE-1879](https://issues.apache.org/jira/browse/LUCENE-1879)" would probably be better

**Comment by mocobeta** [comment]
Relates to #122 - @mikemccand do you have thoughts on it?

**Comment by mikemccand** [comment]
Just repeating what I said on #122 

I'm OK with shortening it somehow if we can, but I think the sentiment must remain -- we need to convey this was a migrated comment to future people who didn't even know we did this issue migration. Maybe "Prior Jira: "? "Migrated Jira: "?  "Old Jira"?

We could remove the by prefix after the : at least?

**Comment by mocobeta** [comment]
Addressed in #128.

**Comment by mocobeta** [comment]
#128 was merged - I'm closing this. Thanks @vlsi and @mikemccand for your suggestions.
