### ISSUE TITLE
Consider using GitHub Pages for attachments rather than raw.githubusercontent.com

### ISSUE THREAD

**Issue by vlsi** [apache/lucene-jira-archive#127]
See https://github.com/mocobeta/forks-migration-test-2/issues/10159#issue-1329359180

raw.githubusercontent.com is not supposed to be used at scale, so it is better to use GitHub pages to avoid rate limits, especially if you implement https://github.com/apache/lucene-jira-archive/issues/126.

Note: it makes sense to add `.nojekyll` file to the attachments repository so GitHub does not try to convert them via Jekyll (see https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/ )

See:
* https://github.com/python-poetry/poetry/issues/976

**Comment by mocobeta** [comment]
Thanks, GitHub pages are actually scalable. I think we need to ask ASF infra (GitHub pages are per user/organization).

**Comment by vlsi** [comment]
> I think we need to ask ASF infra

I do not think so.
GitHub pages is a self-service thing.  See "GitHub Pages" in https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

**Comment by mocobeta** [comment]
> GitHub pages is a self-service thing. See "GitHub Pages" in https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

I didn't notice it, thanks @vlsi!

**Comment by mocobeta** [comment]
I had a bit of trouble with correctly enabling GitHub Pages in this repo, but finally, have done it.
Now attachments are served via GitHub Pages instead of raw.githubusercontent.com.
https://github.com/mocobeta/migration-test-3/issues/594

Many thanks @vlsi for letting us know this.
