### ISSUE TITLE
Should we create links to Jira issues other than Lucene?

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#129]
For example, there are cross-issue links such as `SOLR-XXXX`, `INFRA-XXXX`, or `LEGAL-XXXX`. At least we can/should create links to frequent projects in Lucene?

**Comment by mocobeta** [comment]
I don't think we should cover all ASF Jira projects, but we can list all related projects to Lucene.

![Screenshot from 2022-08-06 22-50-26](https://user-images.githubusercontent.com/1825333/183251762-7a41a505-1c25-474a-a740-00e7d000f740.png)

![Screenshot from 2022-08-06 22-51-50](https://user-images.githubusercontent.com/1825333/183251805-2bf147b5-4a2e-4cc5-95b2-635bf5abbe73.png)

**Comment by mocobeta** [comment]
- PyLucene: https://issues.apache.org/jira/projects/PYLUCENE
- Open Relevance: https://issues.apache.org/jira/projects/ORP
- Solr: https://issues.apache.org/jira/projects/SOLR
- Hadoop: https://issues.apache.org/jira/projects/HADOOP
- ManifoldCF: https://issues.apache.org/jira/projects/CONNECTORS
- Lucene.NET: https://issues.apache.org/jira/projects/LUCENENET
- Mahout: https://issues.apache.org/jira/projects/MAHOUT
- Nutch: https://issues.apache.org/jira/projects/NUTCH
- OpenNLP: https://issues.apache.org/jira/projects/OPENNLP
- Tika: https://issues.apache.org/jira/projects/TIKA/
- Infra: https://issues.apache.org/jira/projects/INFRA
- Legal: https://issues.apache.org/jira/projects/LEGAL

**Comment by vlsi** [comment]
What if you export all the ASF project names and cross-link them?

**Comment by mocobeta** [comment]
> What if you export all the ASF project names and cross-link them?

Can we export all ASF projects? I'm not really familiar with Jira APIs.

**Comment by vlsi** [comment]
See https://issues.apache.org/jira/rest/api/latest/project

**Comment by mocobeta** [comment]
Thanks! I'll try to include all Jira projects - if the regex to capture issue keys is not too slow.

**Comment by vlsi** [comment]
Just in case: the links might come in multiple flavours.

For instance:
* short form: `SOLR-2355`
* URL: `https://issues.apache.org/jira/projects/ARTEMIS/issues/ARTEMIS-3002`
* another URL: `https://issues.apache.org/jira/browse/ARTEMIS-3002`

**Comment by vlsi** [comment]
> is not too slow.

Do you mean `(?:SOLR|LUCENE|...|...)-\d+?` ?
In any case, something like `[A-Z]{2,7}-\d+` should be sufficiently fast, and then you could double-check (via dictionary) if the prefix looks like a valid JIRA project name.

**Comment by mocobeta** [comment]
For this issue, we need to consider only the "short form"; GitHub properly recognizes URLs and automatically generates links for them.

**Comment by vlsi** [comment]
>GitHub properly recognizes URLs and automatically generates links for them.

Just to double-check. Do you already recognize URL-links to LUCENE issues and convert them to "github issue + jira fallback"?

**Comment by mocobeta** [comment]
> Do you already recognize URL-links to LUCENE issues and convert them to "github issue + jira fallback"?

No - we do not touch URL-style links to LUCENE (or other projects) for now. This may be improved in another issue.

**Comment by mocobeta** [comment]
If the authors just paste https://issues.apache.org/jira/browse/LUCENE-10661 in an issue, GitHub interprets it's an ordinary hyperlink. It'd be great if we replace it with `#NN` and completely remove the URL as we do for "short form" references.

**Comment by vlsi** [comment]
There might be issues.apache.org/-style references, see https://github.com/vlsi/bugzilla2github/issues/7

**Comment by mikemccand** [comment]
> If the authors just paste https://issues.apache.org/jira/browse/LUCENE-10661 in an issue, GitHub interprets it's an ordinary hyperlink. It'd be great if we replace it with `#NN` and completely remove the URL as we do so for "short form" references.

Should we spin off a separate issue for this?

**Comment by mocobeta** [comment]
> > If the authors just paste https://issues.apache.org/jira/browse/LUCENE-10661 in an issue, GitHub interprets it's an ordinary hyperlink. It'd be great if we replace it with `#NN` and completely remove the URL as we do so for "short form" references.
> 
> Should we spin off a separate issue for this?

If we know all URL patterns for issues, it'd be easy to address - I'll open another issue for this.

**Comment by mocobeta** [comment]
Addressed in #131.

**Comment by mocobeta** [comment]
#131 seems to work - I'm closing this.

Internal issue links (URLs) to LUCENE Jira will be addressed in #132.
