### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by ikawaha** [apache/lucene-jira-archive#13]
This is a test to check the operation of the issue.

LUCENE-10557 (#7)

**Comment by mocobeta** [comment]
Thank you @ikawaha.
Can you please also add a fake comment please?

**Comment by ikawaha** [comment]
ねこですねこはいますよろしくおねがいします

**Comment by mocobeta** [comment]
Thanks!

**Comment by mocobeta** [comment]
Ok, we can update issues ourselves by scripts.
