### ISSUE TITLE
Archive all Jira attachments

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#2]
All attachments should be archived in `attachments/`. They will be referred from the migrated issues in https://github.com/apache/lucene.
For files with the same names, we keep the latest versions only. (Jira shows links to the latest versions for attachments, so old versions are safely omitted.)

**Comment by mocobeta** [comment]
Attachments are 850MiB in total. It took 8 hours for me to download all Jira issues and their attachments (I set 0.5 second intervals between Jira API calls).
```
lucene-jira-archive $ dust -bc -d 0 attachments/
 848M ┌── attachments
```

**Comment by mocobeta** [comment]
The attachment files were able to be committed/pushed all at once. 
https://github.com/apache/lucene-jira-archive/commit/5a401516378fcc7c76b613aca426739ad7f9a66a

**Comment by mocobeta** [comment]
I deleted all attachments once committed. I think we should have them in a separate branch and it should be orphaned, as not to download too large data (and deltas) when anyone clones this repo. Maybe I will also try to reset the commit history of main.

**Comment by dweiss** [comment]
When people clone, they will clone everything, including orphaned roots/ branches. You can do a shallow clone of a single branch but it's not a default.

**Comment by mocobeta** [comment]
I did:
- "reset --hard" (and force push) to reset the history to the point before https://github.com/apache/lucene-jira-archive/commit/5a401516378fcc7c76b613aca426739ad7f9a66a
- created an orphaned branch `attachments` where all attachments will be archived
- mention about `--single-branch --branch main` in the top level README.

**Comment by mocobeta** [comment]
Instead of `main`, I committed all attachments (the latest snapshot) to `attachments` branch.
The download script looks to work fine. I'm closing this.

**Comment by mocobeta** [comment]
Links that point to the files in the `attachments` branch are also fine.

![Screenshot from 2022-07-02 20-39-13](https://user-images.githubusercontent.com/1825333/176999240-b77f9e0f-ebeb-43b2-85d2-93ec2333e5e7.png)

**Comment by mikemccand** [comment]
Thanks @mocobeta!  This is first time I learned of this cool `dust` command!  What a great name too.

**Comment by mocobeta** [comment]
> This is first time I learned of this cool `dust` command! What a great name too.

Yes, it's one of my favorite CLI tools (a bit slower than `du` but fine for my usage).
