### ISSUE TITLE
Improve the `Jira Information` header?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#27]
I think we should polish the header a bit.  Here is an example of what it looks like now:

```
Jira information
Original Jira: https://issues.apache.org/jira/browse/LUCENE-2230
Reporter: Fuad Efendi
Assignee:
Created: 2010-01-21T20:18:24.387+0000
Updated: 2011-05-17T19:43:13.861+0000
Resolved: None

Issue Links:

Sub-Tasks:

Pull Requests:
```

Could we?:
  * Change the header to `Legacy Jira Details`
  * If there are no issue links, sub tasks, pull requests, Assignee, Resolved, etc., let's not output those empty lines
  * Render original Jira as a hyperlink with issue as the text, i.e. [LUCENE-2230](https://issues.apache.org/jira/browse/LUCENE-2230).  No need for the `Original Jira` header I think?
  *  Render dates like `2010-01-21` (leave off the timestamp, timezone)

So then maybe it could look something like this:

```
Legacy Jira LUCENE-2230
Reporter: Fuad Efendi
Created: 2010-01-21
Updated: 2011-05-17
```

I can maybe take a stab at this ... but I'm have some trouble finding where this text is generated in the Jira export / GitHub import source code...

**Comment by mikemccand** [comment]
> ... but I'm have some trouble finding where this text is generated in the Jira export / GitHub import source code...

[Found it](https://github.com/apache/lucene-jira-archive/blob/main/migration/src/jira2github_import.py#L91)!  Woot!  I'll take a stab...

**Comment by mocobeta** [comment]
For prototyping, it was the easiest way to embed the fixed template for Jira information in the conversion script for me... I agree that there are more sophisticated methods to flexibly generate the Jira information paragraph.

**Comment by mocobeta** [comment]
Hi @mikemccand, I plan to start the next (hopefully last) migration test for all issues on July 25th. Could you merge improvements in your mind for `jira2github_import.py` until then, if possible?
Thanks.

**Comment by mikemccand** [comment]
I think this one is done!
