### ISSUE TITLE
Create mapping on Jira user id -> GitHub account

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#3]
To correctly map Jira user ids in issues (reporter/assignee/author) to GitHub account, we need an account mapping file.
This could be inferred from https://github.com/orgs/apache/people?

**Comment by mocobeta** [comment]
Looks like there's no way to list accounts that belong to a specific organization. Also, it is impossible to make a mapping for non-committers (contributors).

With GitHub API,

1. List all GitHub users
2. Check if each account has push access to `apache/lucene` repo (this hopefully lists all committers' accounts)
3. Associate Jira ids and GitHub accounts by their "display" names

**Comment by mocobeta** [comment]
If you have a better idea for this, please leave your suggestions.

**Comment by mocobeta** [comment]
Tasks to be done:

- [ ] regenerate a candidate mapping (on July 24th)
- [ ] manually make a "verified" mapping and commit it to `main` (on July 24th or 25th)
- [ ] send a mail to the dev list to let others browse/check both "candidate" and "verified" mappings (on July 25th)
- [ ] accept pull requests to add/edit the mapping
- [ ] fix the final mapping (on August 7th)

**Comment by mikemccand** [comment]
Could we maybe look for Jira issues that have GitHub PRs attached and "correlate" the ids of who opened the PR against who commented on the issue?

It would clearly not be perfect, but it could provide input for a human to sift through and carry over some verified accounts.

**Comment by mocobeta** [comment]
We already include merged pull requests' authors (if their GitHub full names are set to the same string as Jira full names).
Maybe we could also consider all opened pull requests' authors.

**Comment by mikemccand** [comment]
> We already include merged pull requests' authors (if their GitHub full names are set to the same string as Jira full names).
Maybe we could also consider all opened pull requests' authors.

OK thanks, but does this only work for committers?

I was thinking if a contributor who is not a committer comments on a Jira issue and also opens a PR, linked to the issue, we could maybe correlate those two events to speculate about ID mapping.  And then verify by hand after.

**Comment by mocobeta** [comment]
"Authors" are not necessarily committers; they literally pull request authors (contributors).
For example https://github.com/apache/lucene/commit/2cf12b8cdcc629617b2d58c0a2a6336679ff9249

**Comment by mocobeta** [comment]
Properly speaking, the current "verified" account mapping includes both committers and commit authors. "commit authors" can be committers or contributors.

```
4. Verify the candidate GitHub accounts by checking  if (1) the GitHub account has push access to [apache/lucene repository](https://github.com/apache/lucene), or (2) the GitHub account has been logged as commit author in the repo's commit history at least once.
```

**Comment by mikemccand** [comment]
OK got it.

Could we expand the matching so that if the userid in jira == the userid in GitHub we strongly suggest a match?  E.g. `mdmarshmallow` would have been matched this way.

Hmm, actually, his presented name (`Marc D'mello`) looks the same [in GitHub](https://github.com/mdmarshmallow) and [Jira](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdmarshmallow).  Oh, wait, no!  One is `Marc D'mello` and the other is `Marc D'Mello` (m vs M).  Maybe we can do a case insensitive comparison?

But I'll push his account to the verified file separately.

**Comment by mocobeta** [comment]
> Could we expand the matching so that if the userid in jira == the userid in GitHub we strongly suggest a match? E.g. mdmarshmallow would have been matched this way.

It'd be easy to pick up such candidates - I think we'd need manually verify all of them.

**Comment by mocobeta** [comment]
I'll try to improve candidate generation and verification steps maybe next week.

**Comment by mocobeta** [comment]
I'm closing this, but we'll accept improvements on mapping until the actual migration.
