### ISSUE TITLE
Why are some Jira issues completely missing?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#37]
Spinoff from #33.

This is not a blocker for migration, more because I'm curious how Jira lost issues and how pervasive this problem might be -- maybe other Apache projects are affected?  Or maybe we are doing something wrong in Lucene ;)

Some Jira issues in the sequential numbering from 1 .. N just don't seem to exist, and seem to have never existing (Google searching, jirasearch, Jira's own (Lucene based!) search engine, my long email archive also fail to find at least one of them):

```
[2022-07-11 07:57:25,815] WARNING:download_jira: Can't download LUCENE-498. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 07:59:10,096] WARNING:download_jira: Can't download LUCENE-613. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 07:59:10,978] WARNING:download_jira: Can't download LUCENE-614. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 07:59:13,615] WARNING:download_jira: Can't download LUCENE-617. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 08:10:36,059] WARNING:download_jira: Can't download LUCENE-1362. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 08:10:36,932] WARNING:download_jira: Can't download LUCENE-1363. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 08:10:37,798] WARNING:download_jira: Can't download LUCENE-1364. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 08:26:22,112] WARNING:download_jira: Can't download LUCENE-2375. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
[2022-07-11 08:27:02,304] WARNING:download_jira: Can't download LUCENE-2418. status code=404, message={"errorMessages":["Issue Does Not Exist"],"errors":{}}
```

Maybe Jira has some concurrency bug in how it numbers issues and sometimes leaves holes?

**Comment by msokolov** [comment]
Maybe somebody did this https://confluence.atlassian.com/jirakb/how-to-set-the-starting-issue-number-for-a-project-318669643.html

**Comment by mikemccand** [comment]
Egads that is wild ;)  It seems like the use case is to start all issues from a bigger number than 1?  Yet, we started at 1, but then have the occasional hole!  Maybe INFRA team somehow bumped these numbers during maintenance windows of Jira?

**Comment by msokolov** [comment]
I mean it seems unlikely -- why would anyone ever do that? But I guess it demonstrates that there is some mechanism for arbitrarily repositioning the "next issue number", so there are no guarantees. Maybe there is some other thing we haven't found yet that violates this assumption we have that numbers increase by one

**Comment by mikemccand** [comment]
We may never fully solve this mystery!  Cold case!

**Comment by madrob** [comment]
Some issues were probably moved to SOLR issues?

**Comment by mikemccand** [comment]
> Some issues were probably moved to SOLR issues?

Oooh I love that theory!

But then, wouldn't they have left some digital breadcrumbs?  Initial email sent to the list as `LUCENE-XXXX`, to my email, etc.?

**Comment by mikemccand** [comment]
Whoa!  I found two of the issues!  Check it out: https://markmail.org/message/ntz5hxrm4lli57oe and https://markmail.org/message/d5t346iwopaqj45x

Apparently it is possible to completely delete an issue entirely :)  That's a scary power but maybe it is limited to PMC members or committers?

Phew, mystery solved.

**Comment by mocobeta** [comment]
This reminds me that we should exclude the moved issues (to Solr or possibly another project) from migration, but can't figure out ways to detect "moved" issues... Jira API returns data for already moved issues such as https://issues.apache.org/jira/browse/LUCENE-4344, but not sure there is a field to decide whether it has been moved or not. (T⌓T)

**Comment by uschindler** [comment]
> This reminds me that we should exclude the moved issues (to Solr or possibly another project) from migration, but can't figure out ways to detect "moved" issues... Jira API returns data for already moved issues such as https://issues.apache.org/jira/browse/LUCENE-4344, but not sure if there is a field to decide whether it has been moved or not. (T⌓T)

I don't know which JIRA API you use. But when you use the offiial "get issue" API to read all information, it is easy to detect; look at the API respose: https://issues.apache.org/jira/rest/api/2/issue/LUCENE-4344

The root object has the "key" of issue. In this case we requested LUCENE-4344, but the JSON response has `{"key": "SOLR-3769",....}` in the response. The key in the JSON is always the canonic issue number. It may also happen that you have a "redirect" to another LUCENE issue number (if somebody moved the issue to solr and then decided to move it back to Lucene).

So to detect "moved" issues, just compare returned key with requested key.

**Comment by mikemccand** [comment]
> So to detect "moved" issues, just compare returned key with requested key.

I remembered that I had the same challenge with [jirasearch](https://jirasearch.mikemccandless.com)!  [This](https://github.com/mikemccand/luceneserver/blob/master/examples/jirasearch/indexJira.py#L272-L290) is how I solved it.  You must iterate the issue history looking for an update to the `Key` field, I think?

But @uschindler's solution is even simpler!  I should fix the jirasearch impl :)

**Comment by uschindler** [comment]
> I don't see any link for deleting an issue in the latest Lucene Jira, but it is surely possible depending on the configuration (I see "Delete" link in another Jira project).

I can delete issues with my account (it is hidden behind the more button at the end of the menu).

**Comment by mocobeta** [comment]
ah okay thanks, we can check the top-level "key" field.

LUCENE-4344's dump data:
```
{
  "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
  "id": "12605464",
  "self": "https://issues.apache.org/jira/rest/api/latest/issue/12605464",
  "key": "SOLR-3769",  <-- 
  "fields": {
 
```

**Comment by mocobeta** [comment]
Other than the "Moved" issues, are there ones we shouldn't migrate?

**Comment by uschindler** [comment]
> ah okay thanks, we can check the top-level "key" field.

Important: Check if the returned top-level "key" field differs from the requested key (in REST URL). Do not use regular expression, just check "JSON key != URL key" (this will then also identify issues moved from Lucene to Solr and then back, in this case they have both a LUCENE-xxx key, but with different suffix).

**Comment by mikemccand** [comment]
> I found I can delete Lucene issues.

With great power comes great responsibility!

This permission is limited to PMC members and site/project Administrators.

**Comment by mocobeta** [comment]
@mikemccand So can you please revoke my project admin role?

**Comment by mocobeta** [comment]
Thanks, now I'm not able to "Delete" issues, so it's limited to project Admins.

**Comment by mocobeta** [comment]
I think in GitHub issues we don't have much access control as Jira.

**Comment by uschindler** [comment]
Delete is sometimes needed when spammers start to create issues. We had that several times.

**Comment by mocobeta** [comment]
> Delete is sometimes needed when spammers start to create issues. We had that several times.

In GitHub, only repository administrators' (infra team) can delete issues.

**Comment by uschindler** [comment]
> > Delete is sometimes needed when spammers start to create issues. We had that several times.
> 
> In GitHub, only repository administrators' (infra team) can delete issues.

I don't think the issue will be as bad as with JIRA, because Github is quite fast to close spam accounts. The number of deleted issues in JIRA also went down in the last few years. So I would not see this as a limitation. In case of a spam attack, INFRA will for sure take care. I have seen discussions on slack when they asked to delete issues or pull requests.

**Comment by mocobeta** [comment]
@mikemccand I'm really sorry but would you please give me admin access for Lucene Jira again? I would need to silence notifications to issues@ list, before starting the final step for Jira (#15).

**Comment by mikemccand** [comment]
> @mikemccand I'm really sorry but would you please give me admin access for Lucene Jira again? I would need to silence notifications to issues@ list as suggested in dev@ list, before starting the final step for Jira (#15).

Ahh yes no worries will do shortly.

**Comment by mikemccand** [comment]
OK done!   Try again?

**Comment by mocobeta** [comment]
@mikemccand thank you, now I can change the project configuration (again).
