### ISSUE TITLE
Which GitHub accont we should/can use for migration?

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#4]
1. We cannot preserve the original Jira issue/comment authors since GitHub API assumes the caller's account is the author and does not allow callers to change it by any means.

2. To import/create issues with GItHub API, you need admin access to the repo and we developers are not allowed to have it.
Actual migration will be done by infra; it seems a personal account was used for the import job when Lucene.NET project migrated their issues to GitHub. See https://github.com/apache/lucenenet/issues/280.

For example, Spring uses an organization account that is not tied to a person (https://github.com/spring-projects/spring-framework/issues/22178). Can we do the same? What organization account is available to us?

**Comment by mocobeta** [comment]
Seems ASF organization has some organization accounts.
https://github.com/orgs/apache/people?query=asf

I'm thinking this account may perfectly fit for the job - I'll ask infra if we can use it as the author account for migrated issues.
https://github.com/asfgit.

cc @uschindler

**Comment by mocobeta** [comment]
This is two-pass migration.

1. First pass: import all issues/comments; this has to be done by an infra account.

I think we can ask infra to use an official ASF bot account (e.g. https://github.com/asfgit) for the first pass. This means the author of all issues/comments will be the bot.

2. Second pass: update issues/comments that include cross-issue links so that the links are re-mapped with GitHub issue numbers; this can be done by a committer account.

For the second pass, I would like to do this part ourselves, since it is the most time-consuming [1], and risky [2] part of the migration process. This means, my account will be noted in each migrated issue/comment header like "edited by mocobeta". I don't want to use my personal account for our migration purpose, but it's more important to avoid any accidents and if there are any accidents, react quickly to them as far as possible; it's a trade-off for me.

[1] It will take > 24h.
[2] It involves lots of REST API calls via the internet and to make matters worse, it is not an idempotent operation.

**Comment by mocobeta** [comment]
If we must use an ASF bot account throughout all processes, I'd break up the second pass into three sub-steps. 
1) dump all issues/comments again from GitHub
2) convert them locally
3) pass the converted result to infra and ask to run the update script

It'll make the total time of the migration longer but make it a bit safer than the current draft plan in #7.

**Comment by mocobeta** [comment]
If there are no comments/objections, I'll decide how we proceed with that.

**Comment by madrob** [comment]
Regarding rate limits, would it be possible to reach out to GitHub directly or through ASF infra to get those temporarily raised?

**Comment by mocobeta** [comment]
I'm not familiar with the relationship between ASF and GitHub, but the ASF organization accounts could possibly be already counted as an Enterprise Account  (with a higher limit of 15,000 requests per hour).

I think the difficulty here is that we developers cannot test our migration script with a real ASF account and [infra would expect us to provide "tested" scripts](https://issues.apache.org/jira/browse/INFRA-20118). If we mistakenly estimate the throttling interval the script will fall into an unstable status in the middle of processing (maybe one or two hours later after starting), and there is no way to roll back. 
Maybe as a possible scenario, we could make the interval tunable and ask infra to set it to an appropriate value, if possible.

**Comment by mocobeta** [comment]
There have been no additional comments/requests.
I decided to use my account for the second pass (updating step after importing) since I don't think we should bother infra with asking to run a time-consuming job that can be done by ourselves.

**Comment by mikemccand** [comment]
> It involves lots of REST API calls via the internet with a strict rate limit, and to make matters worse, it is not an idempotent operation.

Hmm why is the script NOT idempotent?  It remaps a `LUCENE-XXXX` link to a `#YYYY` GitHub link right?  If you ran it again, wouldn't it have nothing to remap?

**Comment by mocobeta** [comment]
> Hmm why is the script NOT idempotent? It remaps a `LUCENE-XXXX` link to a `#YYYY` GitHub link right? If you ran it again, wouldn't it have nothing to remap?

@mikemccand it was not idempotent at that time, but I made it idempotent by this change #16 (in exchange for additional steps/time.)

**Comment by mocobeta** [comment]
> If you ran it again, wouldn't it have nothing to remap?

It's difficult (or at least cumbersome) to correctly determine if there is already a remapped cross-issue link so it "should not do anything", since a cross-issue link is just a string (`#XX`) in plain texts.

**Comment by vlsi** [comment]
@mocobeta , can you please clarify why you have decided to do two-pass migration?

Why don't you just import the issues with the proper cross-references in the first place?

In other words:
1) If you import issues in ascending order, then you can statically predict the generated issue numbers
2) When doing the import, you can wait till the issue is finished, so all of them are generated in order

Here's an example of an issue imported in a single go: https://github.com/vlsi/tmp-jmeter-issues/issues/1188#issue-1327437303

**Comment by mocobeta** [comment]
We could predict the issue numbers as you pointed out, but we must prioritize safety. Importing takes 24 hours and if there are short-time GItHub outages (it's not very uncommon), the numbers would be inconsistent with the predicted issue numbers - it'd be a disaster for us.

In addition, we decided to make GitHub issues available _before_  the migration is finished not to interrupt our issue system while preventing people from opening a new Jira issue; this makes it almost impossible to determine the imported issue numbers.

**Comment by mocobeta** [comment]
There will also be pull requests (we already heavily use it) - @vlsi I'm just curious if there is a way to correctly determine the issue numbers while new issues/PRs are arrived during importing. We won't be able to stop new issues/PRs.

**Comment by vlsi** [comment]
> There will also be pull requests (we already heavily use it)

Just in case: I'm doing the migration for Apache JMeter (see https://github.com/vlsi/bugzilla2github).

>I'm just curious if there is a way to correctly determine the issue numbers while new issues/PRs are arrived during importing

I do not think so. As far as I know, the issues are allocated sequentially, and the latest assigned number can be fetched via https://api.github.com/repos/apache/lucene/issues?per_page=1 API (see `number: 1058`).

With JMeter, the flow of issues and PRs is not really high, so we would just make everything read-only during the migration.

---

> issue numbers while new issues/PRs are arrived during importing

I assume you use bulk issue import API (https://gist.github.com/jonmagic/5282384165e0f86ef105), and if you wait for the import to complete, then it does return the assigned issue_number.

However, the key need for pre-assigning the numbers is that you could generate comments that reference "issues that will be created later". If GitHub breaks, you could just continue from what you stopped.
On the other hand, if you really want to allow creating issues and pull requests during the migration, then you can't easily "reference non-yet-created issues" since every PR created will shift the numbers.

**Comment by vlsi** [comment]
> We won't be able to stop new issues/PRs

Do you know GitHub has "Temporary interaction limits"?

I think it should be able to prevent creating issues and PRs during the import: 
 https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository#about-temporary-interaction-limits

By the way. I wonder if you tried contacting GitHub support somehow.
Lucene is a really popular project, and it might be that you could somehow get GitHub support, so they help you with migrating the issues. For instance, when LLVM migrated their issues to GitHub, they migrated the issues to a temporary GitLab instance, and then GitHub support used a special migratory tool to migrate the issues from GitLab to GitHub. That enabled LLVM to forge commenters (see https://github.com/llvm/bugzilla2gitlab)

**Comment by mocobeta** [comment]
Thanks for your suggestions.

> I think it should be able to prevent creating issues and PRs during the import:

Personally, I wish we could temporarily stop all new issues/PRs during migration, but our community is unlikely to accept it.

**Comment by mikemccand** [comment]
> > I think it should be able to prevent creating issues and PRs during the import:
> 
> Personally, I wish we could temporarily stop all new issues/PRs during migration, but our community is unlikely to accept it.

Actually I think that would be fine.  We could VOTE on it, but such down time is warranted if it de-risks the migration.

**Comment by mocobeta** [comment]
Current two-pass migration is carefully considered and safe, and there is no risk; though I admit it's a bit complicated. I don't think we should change the two-pass migration plan just to shorten the total time a bit?

**Comment by mikemccand** [comment]
Yeah I'm not proposing we change this approach now.

I am proposing we mark both GitHub and Jira read-only during the migration.  I think the community would agree, since/if can de-risk migration.  A two day downtime every 10 years or so seems fine ;)

**Comment by mocobeta** [comment]
Maybe I should have strongly argued we should allow some downtime (no new issues, PRs and comments for one or two days) so that we make the migration plan more simple.

But if we follow the two-pass migration plan written in #7, we do not need any downtime.

**Comment by vlsi** [comment]
Does the second pass generate GitHub notifications for the users mentioned in the issues?
I think those notifications would be too much

**Comment by mocobeta** [comment]
> Does the second pass generate GitHub notifications for the users mentioned in the issues?

We confirmed the second pass does not cause any notifications. It seems GitHub does not trigger any notifications by issue/comments updating API.

**Comment by mikemccand** [comment]
Have we confirmed with INFRA that we can quickly make Jira read-only for just our project (Lucene)?

**Comment by mikemccand** [comment]
> But if we follow the two-pass migration plan written in #7, we do not need any downtime.

OK, as long as we feel the risks are all contained (because you had planned on keeping both issue trackers accessible during the migration), then let's stick with that plan.  I just want to point out that asking the community to freeze one or both issue trackers is fine IMO.

**Comment by mocobeta** [comment]
> Have we confirmed with INFRA that we can quickly make Jira read-only for just our project (Lucene)?

We need to update all Jira issues at the last step. If we want Jira read-only during migration, we ask to infra extra work: make Jira read-only, make Jira writable after the migration, and lastly make Jira read-only again after adding comments to each issue - personally, we don't pursue this way.

**Comment by uschindler** [comment]
Just do this live with the Infra team on Slack. They are very cooperative and fix stuff in realtime. Just make some appointment with them and you can work together with them. We did this several times with migration on Jenkins. They are there to help!

**Comment by mocobeta** [comment]
Yes, but - making a Jira project would not be a quick fix I think? I'm missing something maybe?

**Comment by mocobeta** [comment]
I'll reach INFRA, but If possible, I would like to proceed with the whole process in async-style without real-time conversation using Slack - there is a time difference between me and US/Europe people.

**Comment by mocobeta** [comment]
Don't get me wrong - I appreciate suggestions from all of you. However, there are many things you can easily control but I can't due to several differences (timezone, language fluency, etc.) I have to proceed with this project with my very limited resources and ability if there is no person who is willing to take over this work. 

Please feel free to pick any tasks if you see I'm doing them badly.

**Comment by uschindler** [comment]
Hi mocobeta,
I can also look into stuff if it is going on. On whcih machine do you want to start the meigration? I'd suggest to do this on some server at ASF (like the Jenkins Slave lucene1/lucene2).

Regarding read only: Don't misunderstand me. I just wanted to say: Let's make JIRA and Github Readonly for outsiders. Switching this is easy by chaning the permission scheme on the Project, that's two mouseclicks. We can'T do it ourselves, but I'd really want to enforce this.

I don't think it is a problem to prevent people from opening issues! We just put a message there like "we have some maintenance, you can't open issues at the moment. Please send a message to dev@licene.apache.org, we will take care to create a new issue once all systems are backup and running."

**Comment by uschindler** [comment]
And doing something like changing permission scheme can be done with communication on Slack. That's all. I did this several times.

**Comment by mocobeta** [comment]
> I can also look into stuff if it is going on. On whcih machine do you want to start the meigration? I'd suggest to do this on some server at ASF (like the Jenkins Slave lucene1/lucene2).

Sorry I don't know - I'm not familiar with our ASF infrastructure, but I think the infra team selects a proper machine for the job. Anyway we can't run ourselves.

> Regarding read only: Don't misunderstand me. I just wanted to say: Let's make JIRA and Github Readonly for outsiders. Switching this is easy by chaning the permission scheme on the Project, that's two mouseclicks. We can'T do it ourselves, but I'd really want to enforce this.
> I don't think it is a problem to prevent people from opening issues! We just put a message there like "we have some maintenance, you can't open issues at the moment. Please send a message to [dev@licene.apache.org](mailto:dev@licene.apache.org), we will take care to create a new issue once all systems are backup and running."

Thanks, it'd be great if we make them completely non-writable. I think it'd be fine for Jira side, maybe people wouldn't care much about it. 
For GitHub side, I think we'll need to stop all PRs/reviews as well as issues on GitHub for two or three days ("PR"s are special issues in GitHub). Many people would never imagine it. I have to explain why this is needed on the dev@ list - I'll post an email on it later.

> And doing something like changing permission scheme can be done with communication on Slack. That's all. I did this several times.

Of course, I can use ASF Slack for asynchronous communication. I'll reach the infra team and consult on how to arrange the whole process considering the time difference.

**Comment by mocobeta** [comment]
I recognize strong suggestions to make both Jira and GitHub non-writable during migration. Generally, I agree with it - stopping all activities for two or three days would not be a big deal (hope there are no objections since I've seen at least one request not to stop our issue system).

Allowing downtime, the migration plan will be:
1. Make both Jira and GitHub read-only for everyone including committers. Make sure no one can open issues, pull requests, or add comments to existing issues/PRs.
2. Start migration.
3. Make GitHub issues/PRs available once the migration is completed.
4. Make Jira writable (for only committers, if possible).
5. Add each Jira issue a comment saying "This wad moved to GitHub <URL>"
6. Make Jira read-only.

For details, I'll reach infra by Jira or Slack.

**Comment by mocobeta** [comment]
I sent an email on the dev@ list to share the change in the migration (~72 hours downtime for issues/PRs). I'd be glad if you give further suggestions there.
If there are no strong responses, I will open an INFRA issue to explain our plans/requests. We are still in work-in-progress here, but there are lots of uncertainties in access control in Jira and GitHub to me; I need to clarify a couple of questions on that.

**Comment by vlsi** [comment]
>This wad moved to GitHub 

Are you going to include the link to GitHub issue?
Would that trigger JIRA notifications?

**Comment by mocobeta** [comment]
> Are you going to include the link to GitHub issue?

Yes, this is the main purpose of leaving a comment to each Jira. The message will be something like `This was moved to GitHub. [URL]`

> Would that trigger JIRA notifications?

We plan to completely silence JIRA notifications. If this can't be done ourselves, we'd need to ask infra.

**Comment by mikemccand** [comment]
> This was moved to GitHub. [URL]

Could we make it look something like this:

This issue was moved to GitHub issue [\#517](https://link-to-github-issue).

I.e. embed the link in the Jira comment?

**Comment by mocobeta** [comment]
It's just a hyperlink, we can use any anchor string.

In Jira syntax it would be:
```
This issue was moved to GitHub issue [#517|https://link-to-github-issue/].
```

**Comment by mocobeta** [comment]
Refined the comment message for Jira. See:
https://issues.apache.org/jira/browse/LUCENE-10557?focusedCommentId=17576357&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17576357

![Screenshot from 2022-08-07 19-48-19](https://user-images.githubusercontent.com/1825333/183287167-0524f885-78f0-4943-909f-a56ef12156dc.png)

commit: https://github.com/apache/lucene-jira-archive/commit/3ad68da3d1f04fab55c8496f7cd004b1e9d73d9c

**Comment by mocobeta** [comment]
Hi,
here is the INFRA issue.
https://issues.apache.org/jira/browse/INFRA-23563

Can you please watch the issue, and give comments if needed? I tried to explain our intricate requests but am not so confident that I'm doing well it.

**Comment by mikemccand** [comment]
Thanks @mocobeta!

**Comment by mocobeta** [comment]
Infra created this for issue migration purposes. https://github.com/asfimport. 
The profile icon will be set later.

**Comment by mocobeta** [comment]
I tested it works.
https://github.com/apache/lucene/issues/1070

I'm closing this. Thank you everyone who gave comments on this.
