### ISSUE TITLE
Remove "module" for core components?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#53]
### Description

I noticed we have components like `component:module/core/hnsw`.

Could we remove the `module/` prefix for `core`?  It would make the core component strings shorter, which is meaningful/helpful since they are so frequently used?

The other real modules (e.g. `component:module/facet`) I think should keep their `module/` prefix?

Also, I like the issue template testing here!

**Comment by mocobeta** [comment]
> Could we remove the `module/` prefix for `core`? It would make the core component strings shorter, which is meaningful/helpful since they are so frequently used?

We can omit `module` from it though, I would slightly prefer to have `module` for all components for consistency. This is a bit longer but we'll use the auto-complete feature when adding/editing labels anyway.
I agree that it looks redundant, perhaps it would be better to change the common label prefix from `component` to `module` like  `module:core/index`, `module:analysis`, `module:sandbox`? `component` comes from Jira's `Components` field, then it does not really mean that much on GitHub?

**Comment by mocobeta** [comment]
> Also, could we maybe use `fix-version` and `affects-version` instead of `fixVersion` and `affectsVersion`? I think it is more readable on quick glance with a `-`?
> 
> I noticed there is also a `type:new_feature` -- maybe we can make that `type:new-feature` for consistency?

Sure, I have no opinion about the label format and named them without much consideration. I will update these lines.
https://github.com/apache/lucene-jira-archive/blob/e3ec8c748bc6e2887190f4b7c93288da0d31b0af/migration/src/jira2github_import.py#L158-L168

**Comment by mikemccand** [comment]
> I agree that it looks redundant, perhaps it would be better to change the common label prefix from `component` to `module` like `module:core/index`, `module:analysis`, `module:sandbox`? `component` comes from Jira's `Components` field, then it does not really mean that much on GitHub?

+1, I like that solution!

**Comment by mikemccand** [comment]
Can this be closed now?

**Comment by mocobeta** [comment]
Yes, I think so. I'm closing this.
