### ISSUE TITLE
Module label is sometimes missing?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#59]
I am test importing all Jira issues from 8000 to 9000, and spot checking.

I noticed [this issue](https://github.com/mikemccand/stargazers-migration-test/issues/161), which in Jira is under `modules/highlighter` in Jira, but that label did not carry over to the GitHub issue for some reason?

**Comment by mocobeta** [comment]
This is a bug (typo) in the label mapping; I'll fix this.
https://github.com/apache/lucene-jira-archive/blob/75e70ce3abad1b070a44a0b75e0df96afd3eae65/migration/src/common.py#L193

**Comment by mikemccand** [comment]
> This is a bug (typo) in the label mapping; I'll fix this.

Oooh!  Awesome, thanks for tracking it down!!

**Comment by mikemccand** [comment]
Could we maybe make this map picky/brittle (throw an exception during conversion if we come across a component/module that isn't in this map)?  It would catch such mistakes sooner I think.

**Comment by mikemccand** [comment]
I'm trying to find a way in our Jira instance to see all labels Lucene's issues use, to get a global sense of label usage.  But the closest I can come to is the autosuggest by label, and there I think it might be all labels across all Apache projects since there seem to be way too many labels that would not usually apply to Lucene (C++ etc.) ;)

**Comment by mocobeta** [comment]
> Could we maybe make this map picky/brittle (throw an exception during conversion if we come across a component/module that isn't in this map)?

Yes, I think it'd be better/safe to raise an exception if there is no corresponding key for Jira's Component in the map.

**Comment by mikemccand** [comment]
> I'm trying to find a way in our Jira instance to see all labels Lucene's issues use, to get a global sense of label usage. But the closest I can come to is the autosuggest by label, and there I think it might be all labels across all Apache projects since there seem to be way too many labels that would not usually apply to Lucene (C++ etc.) ;)

Woops, wrong issue ;)
