### ISSUE TITLE
Should we carry over Jira "labels"?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#61]
Some Jira issues have labels, like [this one](https://issues.apache.org/jira/browse/LUCENE-8213) with `labels: performance`.  But when we don't seem to carry over the label to the [GitHub issue](https://github.com/mikemccand/stargazers-migration-test/issues/213) ... should we?

**Comment by mocobeta** [comment]
It was an intentional omission by me. Personally, I don't think we should bloat issue labels in GitHub... should we port all Jira "Labels" to GitHub labels?

**Comment by mikemccand** [comment]
> Personally, I don't think we should bloat issue labels in GitHub... should we port all Jira "Labels" to GitHub labels?

Well, I don't think it is our position (too much lol?) to decide what is bloat and what is not?

I myself do not use Jira labels much, but others seem to.  I feel we should port what is in Jira as best we can (as GitHub's metdata model and import API allow) and not judge what is bloat or not.

Or do you think somehow all the labels in Jira might actually be problematic for GitHub?  Like too high cardinality or something?

**Comment by mikemccand** [comment]
I'm trying to find a way in our Jira instance to see all labels Lucene's issues use, to get a global sense of label usage. But the closest I can come to is the autosuggest by label, and there I think it might be all labels across all Apache projects since there seem to be way too many labels that would not usually apply to Lucene (C++ etc.) ;)

**Comment by mikemccand** [comment]
OK I wrote a simple tool to aggregate all labels from my (nearly complete) jira dump:
```
import os
import glob
import json

with_label_count = 0
label_count = {}
for file_name in glob.glob('jira-dump/*.json'):
    d = json.load(open(file_name))
    labels = d["fields"]["labels"]
    if len(labels) > 0:
        with_label_count += 1
        #print(f'{file_name}: labels {labels}')                                                                                                                                                                                                                                                          
        for label in labels:
            label_count[label] = 1+label_count.get(label, 0)

for label, count in sorted(label_count.items(), key=lambda a: -a[1]):
    print(f'{label} {count}')
```

Results:

```
patch 66
newdev 44
performance 39
newbie 30
vector-based-search 26
easyfix 25
gsoc2014 25
Java9 22
features 21
dead 19
build 17
gsoc2011 16
Java7 14
mentor 13
pull-request-available 13
documentation 13
Java8 12
maybe32blocker 11
random-chains 11
lucene-gsoc-11 11
lucene 11
github-pullrequest 11
analysis 10
IBM-J9 9
gsoc 8
search 8
facet 8
gsoc2012 7
lucene-gsoc-12 7
FastVectorHighlighter 7
patch-available 6
highlighter 6
query 6
suggester 6
docValues 6
test 6
Java11 6
similarity 5
stemmer 4
beginner 4
IndexWriter 4
incomplete_fix 4
missing_fixes 4
classification 4
index 4
sort 4
language 3
snowball 3
chinese 3
tokenization 3
compression 3
diffblue 3
queryparser 3
optimization 3
maven 3
solr 3
highlighting 3
Highlighter 3
stemming 3
fastvectorhighlighter 3
memory 3
perfomance 3
api-change 3
codec 3
bug 2
java8 2
pagination 2
sorting 2
parallelmultisearcher 2
jvm 2
rank 2
contrib 2
Documentation 2
Turkish 2
download 2
javadoc 2
hadoop 2
feature 2
blocker 2
locking 2
faceting 2
parser 2
Java10 2
booleanquery 2
regression 2
improvement 2
ICUFoldingFilterFactory 2
ready-to-commit 2
multi-word 2
synonyms 2
lock 2
release 2
filter 2
Arabic 2
highlight 2
faceted-search 2
EdgeNGramTokenFilter 2
analyzers 2
Java15 2
gsoc2013 2
searcher 2
tokenizer 2
morelikethis 2
jenkins 1
HTMLStripCharFilter 1
index, 1
iterators 1
Encoding 1
Front 1
normalize 1
null 1
codestyle 1
crush 1
multisearcher 1
span 1
synonym 1
score 1
Document 1
geo 1
join 1
DIH 1
Clarification 1
New_Users 1
Sort 1
docs 1
collator 1
ant 1
ivy 1
jar 1
javax 1
Analyzer 1
Ansj 1
plugin 1
Windows 1
antlr 1
hdfs 1
elasticsearch 1
refresh 1
static-analysis 1
scorer 1
clover 1
cache 1
explain 1
IndexReader 1
Highlighting 1
NPE 1
optimize 1
CountFacetRequest 1
LuceneFaq 1
Website 1
invalid 1
links 1
arguments/parameters 1
javadocs 1
indexing 1
soft-delete 1
ClassLoader 1
Thread 1
french 1
german 1
concurrency 1
starter 1
QueryParser 1
deprecated 1
missing 1
LZ4 1
BOM 1
Dependencies 1
IOE 1
update 1
policy 1
split 1
github-import 1
usability 1
EarlyTerminatingSortingCollector 1
paging 1
searchafter 1
sortingmergepolicy 1
spatial 1
spatialsearch 1
distance 1
geometric 1
length 1
short 1
suggest 1
lucene, 1
prefix 1
gradle-master 1
complexPhrase 1
cleanup 1
Impact 1
MultiLevelSkipList 1
SimpleTextCodec 1
discussion 1
gsoc2017 1
exception 1
interrupt 1
nio 1
classifier 1
batch 1
refactoring 1
time 1
error 1
checksum 1
double 1
float 1
int 1
long 1
numeric 1
Stemmer 1
SpanNearQuery 1
setMinimumNumberShouldMatch 1
CoreContainer 1
CoreReload 1
JMX 1
complexqueryparser 1
hang 1
NativeFSLockFactory 1
Java17 1
IDE 1
netbeans 1
applet 1
unsigned 1
grouping 1
neardup 1
CloseableThreadLocal 1
knn 1
android8.0 1
Suggestion 1
flex 1
merge 1
spatialrecursiveprefixtreefieldtype 1
fedora_12 1
tomcat 1
zstandard 1
Java13 1
Java14 1
java11 1
jdk11 1
jdk13 1
jdk14 1
jdk15 1
RegEx 1
bucket 1
security 1
sha1sum 1
curiosity 1
jdk16 1
opennlp 1
parallel 1
ShingleFilter 1
StopFilter 1
StopWords 1
writer 1
fieldcache 1
range 1
attribute 1
whitespace 1
Java16 1
SnapPull 1
failed 1
masterSlave 1
sorl 1
f5 1
test-failure 1
lookup 1
archive 1
dist 1
tests 1
query-parser 1
forbiddenapis 1
BTree 1
flamewar 1
logging 1
group 1
totalGroupCount 1
noob 1
patch-with-test 1
NPE, 1
Null-Safety 1
Scorer 1
```

I think some of these are helpful?  e.g. `vector-based-search`, `performance`, `newdev`, `newbie`.  The highly unstructured nature is indeed a bit ... open-ended.

**Comment by mikemccand** [comment]
Maybe we could import them under a `legacy-jira-label:XXX` to make it clear?

**Comment by mocobeta** [comment]
> Maybe we could import them under a `legacy-jira-label:XXX` to make it clear?

I'm fine with this but it seems there are many labels that do not really make much sense to me like `int`. Could we only preserve labels attached to at least N issues (perhaps N=3)?

**Comment by mikemccand** [comment]
Sorry, I still feel we should not be the judges/arbiters of history here.

Our goal is to faithfully migrate and not pass personal judgement on what should make the cut.  We should not to do any cleaning.  Maybe one of those singleton labels was created by someone so they could remember their issue easily.  They come back some day to find it by label, see we are in Jira, see that we migrated jira labels, try to search for it, fail to find it --> erodes trust.

Have we done such judgement on other Jira metadata?  I.e. are there cases where we could have migrated XYZ from labels (Jira export gave it to us, GitHub import would accept it) but we chose not to?

**Comment by mocobeta** [comment]
> Have we done such judgement on other Jira metadata? I.e. are there cases where we could have migrated XYZ from labels (Jira export gave it to us, GitHub import would accept it) but we chose not to?

There are some Jira metadata that are not ported at all to GitHub labels such as `Priority`, `Resolution`, `Lucene Fields`.
As for already ported metadata, there is no personal judgment.

**Comment by mocobeta** [comment]
Just to note, GitHub's search feature also search labels as well as issue title and body with "partial match". I think we need to be a bit careful about what labels we add to each issue not to increase search noise.

**Comment by mikemccand** [comment]
> Just to note, GitHub's search feature also search labels as well as issue title and body in "partial match" (I do not know what they do though, I imagine GitHub tokenizes labels with some tokenizer and index the tokens). I think we need to be a bit careful about what labels we add to each issue not to increase search noise.

But I think that is Search problem.  And what we consider noise might be signal to people.  Maybe people want to search for bugs related to `jvm` and they want `jvm bugs` to also search labels.  We also should not try to judge noise vs signal in the search experience I feel.

**Comment by mocobeta** [comment]
I merged #68

**Comment by mikemccand** [comment]
Thanks @mocobeta !

**Comment by mocobeta** [comment]
> But I think that is Search problem. And what we consider noise might be signal to people. Maybe people want to search for bugs related to `jvm` and they want `jvm bugs` to also search labels. We also should not try to judge noise vs signal in the search experience I feel.

I agree with you. I've been playing around with GitHub issue search recently; I feel the result ranking is not very intuitive and there is room to be improved.

**Comment by mocobeta** [comment]
Well, GitHub search result is not ranked by relevancy ("newest" sort is the default).

**Comment by mikemccand** [comment]
> Well, GitHub search result is not ranked by relevancy ("newest" sort is the default).

Ugh LOL.  Maybe it will improve with time?  If only it were open-source!  I wonder if it uses Lucene ;)

We always have [jirasearch](https://jirasearch.mikemccandless.com)!  Except I still have to cut it over to GitHub.  And maybe rename it heh.

**Comment by mikemccand** [comment]
> There are some Jira metadata that are not ported at all to GitHub labels such as `Priority`, `Resolution`, `Lucene Fields`.

Thanks @mocobeta.  I've been looking at `Resolution` -- I think it has less noisy and still helpful metadata.  I'll open a separate issue.

**Comment by mikemccand** [comment]
I was curious about the `Lucene Fields`, so I wrote up a quick aggregator of all populated fields on our Jira issues:

```
import os
import glob
import json

field_count = {}
votes_count = {}

for file_name in glob.glob('jira-dump/*.json'):
    d = json.load(open(file_name))
    votes = d['fields']['votes']['votes']
    votes_count[votes] = 1+votes_count.get(votes, 0)
    for field, value in d['fields'].items():
        if value:
            field_count[field] = 1 + field_count.get(field, 0)

for name, count in sorted(field_count.items(), key=lambda a: -a[1]):
    print(f'{name}: {count}')

print('Votes:')
for name, count in sorted(votes_count.items(), key=lambda a: -a[1]):
    print(f'{name}: {count}')
```

Output:

```
-*- mode: compilation; default-directory: "/l/orig-lucene-jira-archive/migration/" -*-
Compilation started at Sun Jul 24 08:17:22

python print_custom_fields.py 
customfield_12310420: 10645
priority: 10645
customfield_12313422: 10645
status: 10645
customfield_12310920: 10645
creator: 10645
reporter: 10645
aggregateprogress: 10645
progress: 10645
votes: 10645
worklog: 10645
issuetype: 10645
customfield_12314020: 10645
project: 10645
watches: 10645
created: 10645
updated: 10645
summary: 10645
comment: 10645
customfield_12311820: 10645
workratio: 10437
description: 10339
customfield_12310120: 9741
resolution: 8699
resolutiondate: 8699
fixVersions: 6945
attachment: 6703
components: 5779
assignee: 5769
versions: 3618
issuelinks: 2164
timetracking: 1515
aggregatetimespent: 1315
timespent: 1307
environment: 1022
labels: 611
customfield_10010: 437
parent: 333
aggregatetimeoriginalestimate: 208
aggregatetimeestimate: 208
timeestimate: 205
timeoriginalestimate: 205
subtasks: 79
customfield_12310250: 63
customfield_12313520: 32
customfield_12311020: 15
duedate: 8
customfield_12311024: 4
Votes:
0: 9802
1: 545
2: 142
3: 63
4: 25
5: 22
6: 10
8: 7
7: 6
12: 5
11: 4
9: 3
14: 2
10: 2
13: 1
22: 1
19: 1
28: 1
16: 1
36: 1
15: 1
```

I guess the Lucene fields are all of these `customer_N` fields ... but they are heavily denormalized on export LOL.  I'll try to sift through them.

**Comment by mocobeta** [comment]
I think "Lucene Fields" has only two values - "New" and "Patch Available". 
![Screenshot from 2022-07-24 21-49-22](https://user-images.githubusercontent.com/1825333/180647747-9770e469-7cfe-4814-b941-9e6f92448177.png)

This is not shown as default though you can enable it when creating an issue (by clicking "Configure Fields" button in the upper right).

**Comment by mikemccand** [comment]
I wonder what is the difference between `creator` and `reporter`?  Oh I see, I (`mikemccand`) can create an issue but list another user as `reporter`.  Curious ;)  I wonder how often that has happened.

**Comment by mikemccand** [comment]
Heh, 13 times too:

```
issue LUCENE-288, fields["reporter"]["name"]='vajda', fields["creator"]["name"]='andi@osafoundation.org'
issue LUCENE-7726, fields["reporter"]["name"]='hossman', fields["creator"]["name"]='uschindler'
issue LUCENE-4864, fields["reporter"]["name"]='mpoindexter', fields["creator"]["name"]='uschindler'
issue LUCENE-5169, fields["reporter"]["name"]='jpountz', fields["creator"]["name"]='watuki'
issue LUCENE-5056, fields["reporter"]["name"]='hdeadman', fields["creator"]["name"]='dsmiley'
issue LUCENE-672, fields["reporter"]["name"]='yseeley@gmail.com', fields["creator"]["name"]='ningli'
issue LUCENE-1264, fields["reporter"]["name"]='bmargulies', fields["creator"]["name"]='bimargulies'
issue LUCENE-346, fields["reporter"]["name"]='cutting', fields["creator"]["name"]='cutting@apache.org'
issue LUCENE-6673, fields["reporter"]["name"]='dancollins', fields["creator"]["name"]='andyetitmoves'
issue LUCENE-228, fields["reporter"]["name"]='vajda', fields["creator"]["name"]='andi@osafoundation.org'
issue LUCENE-289, fields["reporter"]["name"]='vajda', fields["creator"]["name"]='andi@osafoundation.org'
issue LUCENE-359, fields["reporter"]["name"]='cutting', fields["creator"]["name"]='cutting@apache.org'
issue LUCENE-1, fields["reporter"]["name"]='cutting', fields["creator"]["name"]='cutting@apache.org'
```

Looks like we use `reporter` not `creator`, perfect.

**Comment by mikemccand** [comment]
> I think "Lucene Fields" has only two values - "New" and "Patch Available".

OK let's maybe not carry those over?

**Comment by mocobeta** [comment]
> I wonder what is the difference between creator and reporter? Oh I see, I (mikemccand) can create an issue but list another user as reporter. Curious ;) I wonder how often that has happened.

I didn't know that, but I noticed we (reporters? committers?) can set an arbitrary username to `Reporter` fields in Jira.
![Screenshot from 2022-07-25 19-25-11](https://user-images.githubusercontent.com/1825333/180756240-eac5bc0b-c181-437d-b976-9831950362dd.png)

In that case, `reporter` and `creator` is set to different values.
For example, I changed Reporter field in https://issues.apache.org/jira/browse/LUCENE-10557 as follows.
![Screenshot from 2022-07-25 19-29-37](https://user-images.githubusercontent.com/1825333/180756539-47db365b-ef98-434f-8018-ace90fe0e56f.png)

Now, `creator` and `reporter` are different.
```
(.venv) migration $ cat jira-dump/LUCENE-10557.json | jq '.fields.creator.name'
"tomoko"
(.venv) migration $ cat jira-dump/LUCENE-10557.json | jq '.fields.reporter.name'
"mikemccand"
```

**Comment by mocobeta** [comment]
> > I think "Lucene Fields" has only two values - "New" and "Patch Available".
> 
> OK let's maybe not carry those over?

I once considered/looked at it and decided not to carry them over to GitHub - I would do nothing for it if you are ok with that.

**Comment by mikemccand** [comment]
Hmm how about `legacy-jira-priority`?

```
python print_priority.py
Major 6182
Minor 3540
Trivial 604
Blocker 202
Critical 117
```

E.g. "how many times did an issue with merging block a release"?

**Comment by mikemccand** [comment]
Does GitHub have a way to vote (+1) on issues?

Also, do GitHub labels support numeric types?

If we carried over `legacy-jira-votes` how would we search it?  Could we sort by it?

Vote distribution:

```
Votes:
0: 9802
1: 545
2: 142
3: 63
4: 25
5: 22
6: 10
8: 7
7: 6
12: 5
11: 4
9: 3
14: 2
10: 2
13: 1
22: 1
19: 1
28: 1
16: 1
36: 1
15: 1
```

**Comment by mikemccand** [comment]
> I didn't know that, but I noticed we (reporters? committers?) can set an arbitrary username to Reporter fields in Jira.

LOL I did not know either!  Furthermore, you can change it after the fact!  Maybe `creator` cannot be updated but `reporter` can?  Must be for an "on behalf of" sort of situation.

**Comment by mikemccand** [comment]
> I once considered/looked at it and decided not to carry them over to GitHub - I would do nothing for it if you are ok with that.

Yeah +1.  They drop even below my signal/noise threshold ;)

**Comment by mocobeta** [comment]
> Hmm how about `legacy-jira-priority`?

I'm fine with it if it's needed.

> If we carried over `legacy-jira-votes` how would we search it? Could we sort by it?

I don't think issues can be sorted by labels (for now) or it's useful for filtering purposes. I would just log it in the issues' "Jira Information" section - if we want to convert it into labels in the future, we can add issue labels anytime by GitHub APIs.

**Comment by mikemccand** [comment]
> > Hmm how about `legacy-jira-priority`?
> 
> I'm fine with it if it's needed.
> 
> > If we carried over `legacy-jira-votes` how would we search it? Could we sort by it?
> 
> I don't think issues can be sorted by labels (for now) or it's useful for filtering purposes. I would just log it in the issues' "Jira Information" section - if we want to convert it into labels in the future, we can add issue labels anytime by GitHub APIs.

+1, OK I'll make a PR for both.

**Comment by mikemccand** [comment]
Woops, I failed to link the PR properly: https://github.com/apache/lucene-jira-archive/pull/76

**Comment by mikemccand** [comment]
`watches` is a Jira field for people who have explicitly subscribed to updates on a Jira issue.

I don't think GitHub has the same capability?  You can watch at the repo level, but not on individual issues?

So maybe we leave `watches` behind (do not migrate that field to GitHub)?

**Comment by mocobeta** [comment]
> So maybe we leave `watches` behind (do not migrate that field to GitHub)?

I agree with it.

**Comment by mocobeta** [comment]
> You can watch at the repo level, but not on individual issues?

You can watch/unwatch particular issues/PRs by Subscribe/Unsubscribe the issue/PR. (a button with a bell icon is placed in the right panel for that.)

**Comment by mikemccand** [comment]
I think we really should migrate `parent` in some way, since we already migrate the reverse direction (sub-tasks)?

**Comment by mikemccand** [comment]
> > You can watch at the repo level, but not on individual issues?
> 
> You can watch/unwatch particular issues/PRs by Subscribe/Unsubscribe the issue/PR. (a button with a bell icon is placed in the right panel for that.)

Ahh OK, hmm.  But we cannot carry over these watches on behalf of all users, I assume.  Users will have to re-watch the issues they care about (even the legacy Jira ones) again?  We should note this on the "Release Notes" that we send about this migration?  We should advertise the things we chose not to migrate.  Hmm, do we have a draft of these release notes?  I'll open a separate issue.

**Comment by mocobeta** [comment]
> Ahh OK, hmm. But we cannot carry over these watches on behalf of all users, I assume. Users will have to re-watch the issues they care about (even the legacy Jira ones) again? 

Yes. We will add comments to each Jira issue to let all watchers know the corresponding GitHub issue URL at the last step in the migration. The watchers should notice it.

**Comment by mikemccand** [comment]
> > Ahh OK, hmm. But we cannot carry over these watches on behalf of all users, I assume. Users will have to re-watch the issues they care about (even the legacy Jira ones) again?
> 
> Yes. We will add comments to each Jira issue to let all watchers know the corresponding GitHub issue URL at the last step in the migration. The watchers should notice it.

+1.

**Comment by mikemccand** [comment]
OK I looked at all of the fields (listed above) and I think we are done, except for this one!:

> I think we really should migrate `parent` in some way, since we already migrate the reverse direction (sub-tasks)?

I'll open a separate issue for this and work on a PR.  I think it shouldn't be hard.  I plan to just append to the `Legacy Jira Information` header.
