### ISSUE TITLE
Jira username mentions are not converted?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#63]
I noticed [this comment](https://github.com/mikemccand/stargazers-migration-test/issues/213#issuecomment-1192043461) is calling Jira user `[~ben.manes]`.  Should we replace it with the presentation name of the user (Ben Manes), since the Jira username won't necessarily be so recognizable.

Not sure how often this is happening!  In general for all these little issues I'm opening, they are minor and should not block migration.  Net/net the quality of migrated issues looks great overall!

**Comment by mocobeta** [comment]
I recognize this issue. I think It'd be great if we can handle `[~user]` as well as `@user`.
