### ISSUE TITLE
Carry parent issue over

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#79]
Spinoff from #61.

We already carry the other direction (`sub-tasks`).

It looks like 333 issues have a parent.

**Comment by mocobeta** [comment]
GitHub automatically adds mature links if we link from one issue to another issue, but I agree that it'd be good to explicitly mention parent issues.

**Comment by mikemccand** [comment]
OK I have a PR; it renders LUCENE-618 opening description like this:

-----

The last GData - Server commit  does not build due to a wrong commit.
Yonik did not commit all the files in the diff file. There are several sources and packages missing.

The diff - file with the date of 26.06.06 should be applied.
--> http://issues.apache.org/jira/browse/LUCENE-598
26.06.06.diff (644 kb)

could any of the lucene committers apply this patch. Yonik is on the way to Dublin.

Thanks Simon





---
### Legacy Jira

[LUCENE-618](https://issues.apache.org/jira/browse/LUCENE-618) by Simon Willnauer (@s1monw) on Jun 27 2006, resolved Jun 28 2006
Parent: [LUCENE-598](https://issues.apache.org/jira/browse/LUCENE-598)
Attachments: [27.06.06.diff](https://raw.githubusercontent.com/apache/lucene-jira-archive/attachments/attachments/LUCENE-618/27.06.06.diff)
