### ISSUE TITLE
Set assignee field for issues if the account mapping is given

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene-jira-archive#8]
We can set `Assignee` field if the Jira id - GitHub account mapping is given.

**Comment by mocobeta** [comment]
But -  how to test this.

**Comment by mocobeta** [comment]
@mikemccand I invited you to a test repository to test if we can set (migrate) issues' `Assignee` field. An email should have been sent - can you please accept it?

**Comment by dweiss** [comment]
I'm on holidays but I can click on the invitation if I receive one, @mocobeta

**Comment by mikemccand** [comment]
> @mikemccand I invited you to a test repository to test if we can set (migrate) issues' `Assignee` field. An email should have been sent - can you please accept it?
> 
> I tested it with my account (API's caller and issue author), just wanted to confirm it also works for other accounts.

Thanks @mocobeta!  I just accepted the invitation.

**Comment by mocobeta** [comment]
Thank you both, confirmed that the assignee can be ported.

Issue search result
![Screenshot from 2022-07-07 23-52-51](https://user-images.githubusercontent.com/1825333/177804267-77c14495-120d-42b0-b056-b99bfa08b6cd.png)

Issue detail
![Screenshot from 2022-07-07 23-54-05](https://user-images.githubusercontent.com/1825333/177804732-50dd523f-77bd-4bb8-925f-a367340fb1ac.png)

![Screenshot from 2022-07-07 23-54-43](https://user-images.githubusercontent.com/1825333/177804796-2ba2bdb8-bae5-4cde-a5c8-24b27675db1b.png)

**Comment by mikemccand** [comment]
Woot!

**Comment by dweiss** [comment]
Excellent!
