### ISSUE TITLE
Don't substitute the GitHub issue link in the Legacy Jira header

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#92]
I noticed this:

Legacy Jira

[LUCENE-7672](https://issues.apache.org/jira/browse/LUCENE-7672) (https://github.com/mocobeta/forks-migration-test/issues/7638) by Kevin Crosby on Jan 31 2017, updated Jul 19 2020
Attachments: [LUCENE-7672.patch](https://raw.githubusercontent.com/apache/lucene-jira-archive/attachments/attachments/LUCENE-7672/LUCENE-7672.patch)

Contained on [this issue](https://github.com/mocobeta/forks-migration-test/issues/7638).

Notice how we link back to the same issue from the `LUCENE-7672`?  Can we fix that 2nd pass re-linking to NOT apply to the Legacy Jira header?

**Comment by mikemccand** [comment]
That link is just pointing back to the same page you are already on.

**Comment by mocobeta** [comment]
#97 checks if the cross-issue link points to the same page.

**Comment by mikemccand** [comment]
OK I think we can resolve this now?  Thanks @mocobeta!
