### ISSUE TITLE
Are we missing conversion of some ~jira-id references?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#95]
We (@mocobeta!) made a fix to convert ~username references from Jira, but I still see at least [this occurrence](https://github.com/mocobeta/forks-migration-test/issues/7287#issuecomment-1197788154) where the username was not converted to a GitHub `@`-mention for Steve Rowe's Jira account?

**Comment by mocobeta** [comment]
The same reason as #96 - currently there is no Jira user `~steve_rowe`.

**Comment by mikemccand** [comment]
OK I'll resolve this issue as a duplicate of #96 where more discussion has happened.  Thanks @mocobeta.

**Comment by mikemccand** [comment]
Duplicate of #96

**Comment by mikemccand** [comment]
Duplicate of #96

**Comment by mikemccand** [comment]
Well, I tried to mark this as duplicate not as "Completed".  But, I failed.
