### ISSUE TITLE
Some user references don't convert?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#96]
See [this comment](https://github.com/mocobeta/forks-migration-test/issues/7287#issuecomment-1197788249) -- you might have to scroll down to see which comment I'm highlighting.

There is a reference to `[~thetaphi]` in the original Jira, but it converts to `@uschindler` in GitHub, not an actual mention but a code styling.

**Comment by mikemccand** [comment]
This bug happens at least another two times in this converted issue.

**Comment by mocobeta** [comment]
There is no such Jira user `thetaphi`. I think this is the reason the mention is not converted to a hyperlink in the original Jira comment too.
![Screenshot from 2022-07-31 10-01-36](https://user-images.githubusercontent.com/1825333/182005235-b29d20f2-5350-447e-adbf-17ac34feea05.png)

Uwe Schindler's current Jira account is `uschindler` and it is correctly mapped to the GitHub account `@uschindler`.
 https://issues.apache.org/jira/secure/ViewProfile.jspa?name=uschindler.

Maybe, some account maintenance was done at a certain point, and mentions are not remapped then.

**Comment by mikemccand** [comment]
Hmm, the thing is, this form `[~thetaphi]` seems to happen quite often:

```
(.venv) beast3:migration[main]$ grep -ri "\[\~thetaphi\]" jira-dump | wc
    955   32067  335778
```

Maybe @uschindler changed his Jira account / id at some point?  Could we just add a mapping for his old account id too?

**Comment by mikemccand** [comment]
It happens for some other users too:

```
(.venv) beast3:migration[main]$ grep -ri "\[\~" github-import-data/ | wc
    331   15583  214620
```

E.g.:

```
[~karl wright]
[~kwright@metacarta.com]
[~steve_rowe]
```

Could we just add these few users to the mapping file?

Maybe the migration tool could warn if it sees a `[~something]` that failed to map?

**Comment by uschindler** [comment]
"thetaphi" is "uschindler". This was changed when ASF changed to use LDAP for committer access to JIRA. The other account was deleted (I think) or we renamed it, but a JIRA rename does not convert comments.

**Comment by mikemccand** [comment]
OK!  Mystery explained then.  Apache users (committers+) who had different Jira id than their Apache id, got renamed in the LDAP migration.

But this left some broken `[~....]` references as a result.

@mocobeta if you agree, I can try to work up a PR with these "orphaned" jira IDs by just adding to the mappings file?

**Comment by mikemccand** [comment]
Thanks for the history lesson @uschindler.

**Comment by uschindler** [comment]
See: https://issues.apache.org/jira/browse/INFRA-19087

There were many renames and ASF infra asked to open issues like the above.

**Comment by mocobeta** [comment]
> @mocobeta if you agree, I can try to work up a PR with these "orphaned" jira IDs by just adding to the mappings file?

Yes I think it'd be great if we could add the correct mappings for them.

**Comment by mocobeta** [comment]
But the situation is not any worse than in Jira - anyway, the orphaned mentions are not actual mentions in Jira. I don't think this has priority.

**Comment by uschindler** [comment]
> But the situation is not any worse than in Jira - anyway, the orphaned mentions are not actual mentions in Jira. I don't think this has priority in terms of migration. I think it would be a kind of a nice to have thing though.

I agree. As said before, when you rename users in JIRA it also does not go through all coments and replace mentions. It also does not replace moved issues in mentions (this is why they have redirect).

If we have known renamed users, we should add them to mapping table. I'd suggest this for my name: "thetaphi" -> "uschindler"

**Comment by mocobeta** [comment]
> I'd suggest this for my name: "thetaphi" -> "uschindler"

OK I will do this.

**Comment by mocobeta** [comment]
I would rather try to seek help for #102 - I don't have any clues about this and gave up.

**Comment by mocobeta** [comment]
Seeing the case of "Karl Wright is daddywri" in #102, I feel like we have to investigate all "orphaned" mentions. I'll try to write scripts that count the number of occurrences for mentions like `[~steve_rowe]`. The top mentions in the comments would give us further clues to identify the mapping.

**Comment by mocobeta** [comment]
I committed a script that counts "orphaned" jira usernames in [this branch](https://github.com/apache/lucene-jira-archive/tree/orphan-mentions).

The list is here - usernames are sorted by # of issues where the username appears.
https://github.com/apache/lucene-jira-archive/blob/orphan-mentions/migration/work/ohphan_jira_ids.txt

For example, `thetaphi` is the most frequent and `steve_rowe` is the second.

**Comment by mikemccand** [comment]
Thanks @mocobeta -- can we commit this to the main branch?  I can try to add mappings for the orphan accounts, and then iterate on the still unmapped cases.

**Comment by mocobeta** [comment]
@mikemccand Could you take a look at #103?

**Comment by mocobeta** [comment]
Can we close this?

**Comment by mikemccand** [comment]
Yes, sorry for the delay!
